
GET http://localhost:8080/orion/api/v1/students/hello
Authorization: Basic joao 123

###
GET http://localhost:8080/orion/api/v1/protected/students
Authorization: Basic joao 123

###
# ?sort=name,desc&sort=id,asc
GET http://localhost:8080/orion/api/v1/admin/students/pages?sort=name,asc&sort=id,asc
Authorization: Basic maria 123


###

GET http://localhost:8080/orion/api/v1/protected/students/1
Authorization: Basic joao 123

###

GET http://localhost:8080/orion/api/v1/protected/students/name/oao 5
Authorization: Basic joao 123

###

POST http://localhost:8080/orion/api/v1/admin/students
Authorization: Basic joao 123
content-type: application/json

{
    "id": 25,
    "name": "teste alteração"
}

###

DELETE  http://localhost:8080/orion/api/v1/admin/students/5
Authorization: Basic maria 123
content-type: application/json


### JWT

POST http://localhost:8080/orion/api/login
content-type: application/json

{
    "username": "maria",
    "password": "123"
}
