GET http://localhost:8080/orion/api/students?sort=nome,desc&page=2&size=5

###

GET http://localhost:8080/orion/api/students/3

###
GET http://localhost:8080/orion/api/students/name/ia

###

POST http://localhost:8080/orion/api/students
content-type: application/json

{
    "id": 1,
    "name": "test"
}

###

DELETE  http://localhost:8080/orion/api/students
content-type: application/json

{
    "id": 1,
    "name": "John Lennon"
}

###

PUT http://localhost:8080/orion/api/students
content-type: application/json

{
    "id": 2,
    "name": "John Lennon"
}
