
GET http://localhost:8080/orion/api/students/hello
Authorization: Basic joao 123

###

GET http://localhost:8080/orion/api/students
Authorization: Basic joao 123


###

GET http://localhost:8080/orion/api/students/1
Authorization: Basic joao 123

###

GET http://localhost:8080/orion/api/students/name/ia
Authorization: Basic joao 123

###

POST http://localhost:8080/orion/api/students
Authorization: Basic joao 123
content-type: application/json

{
    "id": 1,
    "name": "test"
}

###

DELETE  http://localhost:8080/orion/api/students/2
Authorization: Basic maria 123
content-type: application/json


###

PUT http://localhost:8080/orion/api/students
content-type: application/json

{
    "id": 2,
    "name": "John Lennon"
}
